# ================================================================================================
# base -> builder -> build-dev     -> ci
#                 -> build-release -> deploy
#                 -> build-migrations
# ================================================================================================
FROM python:3.12-slim as base

ENV PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1 \
    UV_BREAK_SYSTEM_PACKAGES=1 \
    UV_NO_CACHE_DIR=1

ENV PATH="/usr/bin:${PATH}"
RUN ln -sf /usr/local/bin/python /usr/bin/python

WORKDIR /base

# ================================================================================================
FROM base as builder

RUN pip install uv

# ================================================================================================
FROM builder AS build-dev

ENV PYTHONPYCACHEPREFIX="/tmp"

# ================================================================================================
FROM build-dev AS ci

COPY pyproject.toml uv.dev.lock* .
RUN uv venv --python=/usr/bin/python && \
    if [ ! -f uv.dev.lock ]; then \
        uv pip compile --all-extras --output-file=uv.dev.lock pyproject.toml ; \
    fi && \
    uv pip install --python=.venv/bin/python --requirement=uv.dev.lock

COPY lib lib
COPY resources resources
COPY tests tests

RUN uv pip --python=.venv/bin/python install .

# ================================================================================================
FROM builder AS build-release

COPY pyproject.toml uv.lock* .
RUN uv venv --python=/usr/bin/python /.build && \
    if [ ! -f uv.lock ]; then \
        uv pip compile --output-file=uv.lock pyproject.toml ; \
    fi && \
    uv pip install --python=/.build/bin/python --requirement=uv.lock

COPY lib lib
RUN uv pip install --python=/.build/bin/python .

COPY entrypoints entrypoints

# ================================================================================================
FROM cgr.dev/python:latest as deploy

# ================================================================================================
FROM builder as build-migrations

ENV PYTHONPYCACHEPREFIX="/tmp"

COPY migrator/pyproject.toml migrator/uv.lock .
RUN uv pip install --requirement=uv.lock --system

COPY database/migrations migrations
COPY migrator/migrate.py .
ENTRYPOINT [ "python", "/base/migrate.py" ]
